version: '3.8'

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph-snomed
    ports:
      - "8182:8182"  # Gremlin Server port
      - "8184:8184"  # Management API port
    environment:
      # JanusGraph configuration
      JANUS_PROPS_TEMPLATE: cql-es
      janusgraph.storage.backend: cql
      janusgraph.storage.hostname: cassandra
      janusgraph.index.search.backend: elasticsearch
      janusgraph.index.search.hostname: elasticsearch
      # Memory settings
      JAVA_OPTIONS: "-Xms512m -Xmx2g"
    volumes:
      - janusgraph_data:/opt/janusgraph/data
      - ./config/janusgraph:/opt/janusgraph/conf/custom
    networks:
      - janusgraph-network
    depends_on:
      - cassandra
      - elasticsearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra:
    image: cassandra:3.11
    container_name: cassandra-snomed
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: janusgraph-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - janusgraph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe cluster"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: elasticsearch:6.8.23
    container_name: elasticsearch-snomed
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx1g"
      xpack.security.enabled: false
      xpack.monitoring.enabled: false
      xpack.watcher.enabled: false
      xpack.ml.enabled: false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - janusgraph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Milvus Vector Database (Simplified Setup)
  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - COMMON_STORAGETYPE=local
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"  # Milvus gRPC port
      - "9091:9091"    # Milvus HTTP port
    networks:
      - janusgraph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5

volumes:
  janusgraph_data:
  cassandra_data:
  elasticsearch_data:
  milvus_data:

networks:
  janusgraph-network:
    driver: bridge 